resources:
  - repo: self
  
trigger: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: stage1
  jobs:
  - template: ./storage/build/job.yml

- stage: stage2
  jobs:
  - template: ./acr/build/job.yml

- stage: stage3
  jobs:
  - template: ./keyVault/build/job.yml
    parameters:
      keyVaultName: 'keyvaultasfran12'

- stage: stage4
  jobs:
  - template: ./nsg/build/job.yml

- stage: stage5
  jobs:
  - template: ./vnet/build/job.yml

- stage: stage6
  jobs:
  - template: ./webappfront/build/job.yml

- stage: stage7
  jobs:
  - template: ./waf/build/job.yml

- stage: stage8
  jobs:
  - template: ./frontDoor/build/job.yml

- stage: stage9
  jobs:
  - template: ./logicapp/build/job.yml

- stage: stage10
  jobs:
  - template: ./functionApp/build/job.yml    
    parameters:
      functionAppName: 'functionUploadAssessmentFran'

- stage: stage11
  jobs:
  - template: ./functionApp/build/job.yml    
    parameters:
      functionAppName: 'functionDeleteAssessmentFran'


